---
output: 
  github_document:
        pandoc_args: ["--smart"]
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
---

### Code Sharing

There is an ongoing effort in many fields to improve data-sharing, transparency, and reproducibility of analytic results. Sharing analytic code is an integral part of transparency and reproducibility. While sharing data does have some complexities--such as, patient protected health information and data ownership issues--sharing analytic code is straightforward and without regulatory hurdles. Sharing analytic code can increase its use by other researchers, and broaden the impact of the research. Moreover, knowing your code is freely available may lead researchers to engage in better coding practices. Despite its simplicity and value, few journals request or require submission of analytic code along with the manuscript.

In the spirit of collaboration, transparency, and advancing knowledge, I am posting analytic code I've written for various peer-reviewed manuscripts. My hope is others will find the code useful, see the value and begin (or continue) to publish their own code. I also hope journals will see the value and begin to publish analytic code alongside each manuscript.

* [Published Manuscripts](#published-manuscripts)  
* [Manuscripts Under Review](#manuscripts-under-review)

---

### Published Manuscripts

Sjoberg DD, Vickers AJ, Assel M, Dahlin A, Poon BY, Ulmert D, Lilja H. *Twenty-year Risk of Prostate Cancer Death by Midlife Prostate-specific Antigen and a Panel of Four Kallikrein Markers in a Large Population-based Cohort of Healthy Men.* European Urology. 2018 Mar 5. [doi:10.1016/j.eururo.2018.02.016](https://doi.org/10.1016/j.eururo.2018.02.016)    

* [Analysis - Discrimination of PSA and KLK Panel (c-index).do](https://github.com/ddsjoberg/Manuscript-Code-Share/blob/master/Analysis%20Code/2018/Analysis%20-%20Discrimination%20of%20PSA%20and%20KLK%20Panel%20(c-index).do)  
* [Analysis - Reclassification by KLK Panel and Cumulative Incidence.do](https://github.com/ddsjoberg/Manuscript-Code-Share/blob/master/Analysis%20Code/2018/Analysis%20-%20Reclassification%20by%20KLK%20Panel%20and%20Cumulative%20Incidence.do)  

The analysis file(s) require user-written Stata \*.ado files.  A library of the \*.ado files is available for download at [https://github.com/ddsjoberg/stata-ado-library](https://github.com/ddsjoberg/Stata-ado-Library).    

---

Bochner BH, Dalbagni G, Marzouk KH, Sjoberg DD, Lee J, Donat SM, Coleman JA, Vickers A, Herr HW, Laudone VP. *Randomized Trial Comparing Open Radical Cystectomy and Robot-assisted Laparoscopic Radical Cystectomy: Oncologic Outcomes.* European urology. 2018 May 18. [doi:10.1016/j.eururo.2018.04.030](https://doi.org/10.1016/j.eururo.2018.04.030)  

* [Analysis - Lee Robot vs Open RC Recurrence Comparison 10-016.do](https://github.com/ddsjoberg/Manuscript-Code-Share/blob/master/Analysis%20Code/2018/Analysis%20-%20Lee%20Robot%20vs%20Open%20RC%20Recurrence%20Comparison%2010-016.do) 

The analysis file(s) require user-written Stata \*.ado files.  A library of the \*.ado files is available for download at [https://github.com/ddsjoberg/stata-ado-library](https://github.com/ddsjoberg/Stata-ado-Library).    

### Manuscripts Under Review

---  

